name: Seamster
layout_spectrum: 0.06373983159108032
typography_spectrum: 0.23848880515775026
color:
  brandColors:
    - '#105B63'
    - '#FFFAD5'
    - '#FFD34E'
    - '#DB9E36'
    - '#BD4932'
  brandStrength: 0.25846525026245576
  lightness: 0.37731388666427296
  saturation: 0.7586150989512738
  rhythmicContrast: 0.3980143514430464
title: SEAMSTER.CLUB
description: 'custom threads: meet your seamster, or diy'
navigation:
  - name: "friendsday.fi ♻️\uD83D\uDC97\uD83D\uDC56"
    url: 'http://friendsday.fi/'
    type: external
  - name: "softfab.org \uD83D\uDCD0\uD83D\uDC55"
    url: 'https://softfab.org/'
    type: external
  - name: seamster.club manifesto
    id: aff43b26-e15b-4f9e-951d-831465eb0241
    type: content
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/90cd9c54-0e57-43cf-8a4a-fea239ac42ce.png">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/90cd9c54-0e57-43cf-8a4a-fea239ac42ce.png
    metadata:
      '@type': MediaObject
      '@context': 'http://schema.org'
      keywords: []
      publisher:
        name: The-grid-user-content
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
      author: []
      starred: false
      description: ''
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
github: true
